

-- KategorijaKupca

DROP TABLE IF EXISTS KategorijaKupca;

CREATE TABLE KategorijaKupca (
    idKategorijaKupca INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv             VARCHAR(100) NOT NULL,
    popust            INTEGER      NOT NULL
);

INSERT INTO KategorijaKupca (idKategorijaKupca, naziv, popust) VALUES
    (1, 'Redovan',   0),
    (2, 'VIP',      10),
    (3, 'Zlatni',   20);


-- Pekar

DROP TABLE IF EXISTS Pekar;

CREATE TABLE Pekar (
    idPekar        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ime            VARCHAR(50)  NOT NULL,
    prezime        VARCHAR(50)  NOT NULL,
    korisnickoIme  VARCHAR(50)  NOT NULL UNIQUE,
    lozinka        VARCHAR(50)  NOT NULL,
    telefon        VARCHAR(20)
);

INSERT INTO Pekar (idPekar, ime, prezime, korisnickoIme, lozinka, telefon) VALUES
    (1, 'Jovan',  'Janjusevic', 'jjovan02',  'jovan123',  '0641234567'),
    (2, 'Marko',  'Markovic',   'mmarkovic', 'marko123',  '0651234567');


-- Kupac

DROP TABLE IF EXISTS Kupac;

CREATE TABLE Kupac (
    idKupac           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ime               VARCHAR(50)  NOT NULL,
    prezime           VARCHAR(50)  NOT NULL,
    email             VARCHAR(100) NOT NULL,
    idKategorijaKupca INTEGER      NOT NULL,
    CONSTRAINT fk_kupac_kategorija
        FOREIGN KEY (idKategorijaKupca)
        REFERENCES KategorijaKupca(idKategorijaKupca)
);

INSERT INTO Kupac (idKupac, ime, prezime, email, idKategorijaKupca) VALUES
    (1, 'Petar', 'Petrovic', 'petar@gmail.com', 1),
    (2, 'Ana',   'Anic',     'ana@gmail.com',   2);


-- Pecivo

DROP TABLE IF EXISTS Pecivo;

CREATE TABLE Pecivo (
    idPecivo    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv       VARCHAR(100)   NOT NULL,
    opis        VARCHAR(250),
    rokTrajanja VARCHAR(50),
    cena        DOUBLE         NOT NULL
);

INSERT INTO Pecivo (idPecivo, naziv, opis, rokTrajanja, cena) VALUES
    (1, 'Kifla',    'Mekana kifla',   '1 dan',   50.0),
    (2, 'Kroasan',  'Masleni kroasan','2 dana',  120.0),
    (3, 'Zemicka',  'Obicna zemicka', '1 dan',   40.0);


-- Sertifikat

DROP TABLE IF EXISTS Sertifikat;

CREATE TABLE Sertifikat (
    idSertifikat INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv        VARCHAR(100) NOT NULL,
    institucija  VARCHAR(100) NOT NULL
);

INSERT INTO Sertifikat (idSertifikat, naziv, institucija) VALUES
    (1, 'Master pekar',       'Pekarska skola Beograd'),
    (2, 'Higijena u pekarstvu', 'Institut za javno zdravlje');


-- Racun

DROP TABLE IF EXISTS Racun;

CREATE TABLE Racun (
    idRacun        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datumIzdavanja DATE         NOT NULL,
    brojStavki     INTEGER      NOT NULL,
    ukupanIznos    DOUBLE       NOT NULL,
    tipPlacanja    VARCHAR(20)  NOT NULL,
    popust         INTEGER      NOT NULL,
    iznosSaPopustom DOUBLE      NOT NULL,
    idPekar        INTEGER      NOT NULL,
    idKupac        INTEGER      NOT NULL,
    CONSTRAINT fk_racun_pekar
        FOREIGN KEY (idPekar) REFERENCES Pekar(idPekar),
    CONSTRAINT fk_racun_kupac
        FOREIGN KEY (idKupac) REFERENCES Kupac(idKupac)
);


-- StavkaRacuna

DROP TABLE IF EXISTS StavkaRacuna;

CREATE TABLE StavkaRacuna (
    idRacun  INTEGER NOT NULL,
    rb       INTEGER NOT NULL,
    cena     DOUBLE  NOT NULL,
    kolicina INTEGER NOT NULL,
    iznos    DOUBLE  NOT NULL,
    idPecivo INTEGER NOT NULL,
    PRIMARY KEY (idRacun, rb),
    CONSTRAINT fk_stavka_racun
        FOREIGN KEY (idRacun)  REFERENCES Racun(idRacun),
    CONSTRAINT fk_stavka_pecivo
        FOREIGN KEY (idPecivo) REFERENCES Pecivo(idPecivo)
);


-- PS  (Pekar - Sertifikat)

DROP TABLE IF EXISTS PS;

CREATE TABLE PS (
    idPekar      INTEGER NOT NULL,
    idSertifikat INTEGER NOT NULL,
    datumIzdavanja DATE  NOT NULL,
    PRIMARY KEY (idPekar, idSertifikat),
    CONSTRAINT fk_ps_pekar
        FOREIGN KEY (idPekar)      REFERENCES Pekar(idPekar),
    CONSTRAINT fk_ps_sertifikat
        FOREIGN KEY (idSertifikat) REFERENCES Sertifikat(idSertifikat)
);

INSERT INTO PS (idPekar, idSertifikat, datumIzdavanja) VALUES
    (1, 1, '2022-06-15'),
    (1, 2, '2023-03-10');
