/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.sf.jasperreports.engine.*;
import model.Racun;
import model.StavkaRacuna;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import style.Stil;

/**
 *
 * @author stari
 */
public class DetaljiRacunaForm extends javax.swing.JDialog {

    private Racun racun;

    public DetaljiRacunaForm(java.awt.Window parent, boolean modal, Racun racun) {
        super(parent, ModalityType.APPLICATION_MODAL);
        this.racun = racun;
        initComponents();
        setTitle("Detalji računa #" + racun.getIdRacun());
        setLocationRelativeTo(parent);
        setResizable(false);
        popuniPolja();
        stilizuj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblIdRacun = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblPekar = new javax.swing.JLabel();
        lblKupac = new javax.swing.JLabel();
        lblTipPlacanja = new javax.swing.JLabel();
        lblPopust = new javax.swing.JLabel();
        lblUkupno = new javax.swing.JLabel();
        lblSaPopustom = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnZatvori = new javax.swing.JButton();
        btnStampaj = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblIdRacun.setText("ID računa");

        lblDatum.setText("Datum");

        lblPekar.setText("Pekar");

        lblKupac.setText("Kupac");

        lblTipPlacanja.setText("Tip plaćanja");

        lblPopust.setText("Popust");

        lblUkupno.setText("Ukupan iznos");

        lblSaPopustom.setText("Iznos sa popustom");

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavke);

        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        btnStampaj.setText("Štampaj");
        btnStampaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStampajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStampaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZatvori))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSaPopustom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addComponent(lblUkupno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPopust, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipPlacanja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKupac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPekar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIdRacun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblIdRacun)
                .addGap(16, 16, 16)
                .addComponent(lblDatum)
                .addGap(16, 16, 16)
                .addComponent(lblPekar)
                .addGap(16, 16, 16)
                .addComponent(lblKupac)
                .addGap(16, 16, 16)
                .addComponent(lblTipPlacanja)
                .addGap(16, 16, 16)
                .addComponent(lblPopust)
                .addGap(16, 16, 16)
                .addComponent(lblUkupno)
                .addGap(16, 16, 16)
                .addComponent(lblSaPopustom)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZatvori)
                    .addComponent(btnStampaj, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void btnStampajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStampajActionPerformed
        System.out.println("Broj stavki u racunu: " + racun.getStavke().size());
        for (model.StavkaRacuna s : racun.getStavke()) {
            System.out.println("  -> " + s.getRb() + " | " + s.getNazivPeciva() + " | " + s.getKolicina() + " | " + s.getIznos());
        }
        try {
            Map<String, Object> parametri = new HashMap<>();
            parametri.put("idRacun",         racun.getIdRacun());
            parametri.put("datum",           racun.getDatumIzdavanja().toString());
            parametri.put("pekar",           racun.getPekar().getIme() + " " + racun.getPekar().getPrezime());
            parametri.put("kupac",           racun.getKupac().getIme() + " " + racun.getKupac().getPrezime());
            parametri.put("tipPlacanja",     racun.getTipPlacanja());
            parametri.put("popust",          racun.getPopust());
            parametri.put("ukupanIznos",     racun.getUkupanIznos());
            parametri.put("iznosSaPopustom", racun.getIznosSaPopustom());

            // Putanja do report/ foldera
            parametri.put("SUBREPORT_DIR", "report/");

            // Lista stavki racuna - ovo ide u subreport
            JRBeanCollectionDataSource stavkeDs = new JRBeanCollectionDataSource(racun.getStavke());
            parametri.put("SUBREPORT_DATA_SOURCE", stavkeDs);

            List<Object> jednoClanLista = Arrays.asList(new Object());
            JRBeanCollectionDataSource mainDs =new JRBeanCollectionDataSource(jednoClanLista);

            JasperPrint jprint = JasperFillManager.fillReport("report/Racun.jasper", parametri, mainDs);

            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setTitle("Izveštaj — Račun #" + racun.getIdRacun());
            viewer.setAlwaysOnTop(true);
            viewer.setVisible(true);
            dispose(); 

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"Greška pri štampanju izveštaja:\n" + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnStampajActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStampaj;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblIdRacun;
    private javax.swing.JLabel lblKupac;
    private javax.swing.JLabel lblPekar;
    private javax.swing.JLabel lblPopust;
    private javax.swing.JLabel lblSaPopustom;
    private javax.swing.JLabel lblTipPlacanja;
    private javax.swing.JLabel lblUkupno;
    private javax.swing.JTable tblStavke;
    // End of variables declaration//GEN-END:variables

    private void popuniPolja() {
       
        lblIdRacun.setText("ID računa: " + racun.getIdRacun());
        lblDatum.setText("Datum: " + racun.getDatumIzdavanja().toString());
        lblPekar.setText("Pekar: " + racun.getPekar().getIme()+ " " + racun.getPekar().getPrezime());
        lblKupac.setText("Kupac: " + racun.getKupac().getIme()+ " " + racun.getKupac().getPrezime());
        lblTipPlacanja.setText("Tip plaćanja: " + racun.getTipPlacanja());
        lblPopust.setText("Popust: " + racun.getPopust() + "%");
        lblUkupno.setText("Ukupan iznos: "+ String.format("%.2f", racun.getUkupanIznos()) + " RSD");
        lblSaPopustom.setText("Iznos sa popustom: "+ String.format("%.2f", racun.getIznosSaPopustom()) + " RSD");
        tblStavke.setModel(new view.model.StavkaRacunaTableModel(racun.getStavke()));
    
    }

    private void stilizuj() {
        Stil.labela(lblDatum);
        Stil.labela(lblIdRacun);
        Stil.labela(lblKupac);
        Stil.labela(lblPekar);
        Stil.iznosLabela(lblPopust);
        Stil.iznosLabela(lblSaPopustom);
        Stil.labela(lblTipPlacanja);
        Stil.iznosLabela(lblUkupno);
        Stil.pozadina(getContentPane());
        Stil.crveno(btnZatvori);
        Stil.tabela(tblStavke);
        Stil.scrollPanel(jScrollPane1);
        Stil.tabela(tblStavke); 
        Stil.plavo(btnStampaj);
    }
    
    
    
}
