package model.communication;

public enum Operation {
    LOGIN,

    // KategorijaKupca
    KREIRAJ_KATEGORIJA_KUPCA,
    LISTA_SVI_KATEGORIJA_KUPCA,
    LISTA_NEKI_KATEGORIJA_KUPCA,
    OBRISI_KATEGORIJA_KUPCA,
    PROMENI_KATEGORIJA_KUPCA,

    // Pecivo
    KREIRAJ_PECIVO,
    LISTA_SVI_PECIVO,
    LISTA_NEKI_PECIVO,
    OBRISI_PECIVO,
    PROMENI_PECIVO,

    // Pekar
    KREIRAJ_PEKAR,
    LISTA_SVI_PEKAR,
    LISTA_NEKI_PEKAR,
    OBRISI_PEKAR,
    PROMENI_PEKAR,

    // Sertifikat
    UBACI_SERTIFIKAT,
    LISTA_SVI_SERTIFIKAT,
    LISTA_NEKI_SERTIFIKAT,
    OBRISI_SERTIFIKAT,
    PROMENI_SERTIFIKAT,

    // Kupac
    KREIRAJ_KUPAC,
    LISTA_SVI_KUPAC,
    LISTA_NEKI_KUPAC,
    OBRISI_KUPAC,
    PROMENI_KUPAC,

    // Racun
    KREIRAJ_RACUN,
    LISTA_SVI_RACUN,
    LISTA_NEKI_RACUN,
    PROMENI_RACUN,
    
    VRATI_AI_PREPORUKU
}
